In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [4]:
pheno = pd.read_csv("./feno.txt")
geno = pd.read_csv("./geno.txt")
y = pheno["Congo_red"]

In [5]:
y.describe()

count    979.000000
mean      -0.580926
std        6.411729
min      -13.488314
25%       -6.620026
50%       -0.568692
75%        4.537839
max       15.984204
Name: Congo_red, dtype: float64

In [6]:
geno.describe()

,27915_chr01_27915_T_C,28323_chr01_28323_G_A,28652_chr01_28652_G_T,29667_chr01_29667_C_A,30756_chr01_30756_C_G,31059_chr01_31059_G_A,31213_chr01_31213_G_A,31636_chr01_31636_T_C,31756_chr01_31756_C_T,31976_chr01_31976_C_T,...,12048322_chr16_925487_A_C,12048577_chr16_925742_T_A,12049012_chr16_926177_C_T,12050738_chr16_927903_A_C,12050938_chr16_928103_C_T,12052353_chr16_929518_C_T,12052559_chr16_929724_A_G,12053380_chr16_930545_A_T,12054124_chr16_931289_T_C,12054779_chr16_931944_C_T
count,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,...,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,0.523810,0.522817,0.523810,0.524802,0.525794,0.526786,0.527778,0.528770,0.529762,0.530754,...,0.509921,0.508929,0.507937,0.501984,0.500992,0.500000,0.500992,0.500000,0.500992,0.501984
std,0.499681,0.499727,0.499681,0.499632,0.499582,0.499530,0.499476,0.499419,0.499361,0.499301,...,0.500150,0.500168,0.500185,0.500244,0.500247,0.500248,0.500247,0.500248,0.500247,0.500244
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,0.500000,1.000000,1.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
missing_phenos = y[ y.isnull() ].index.values
geno = geno.drop( missing_phenos, axis = 0)
y = y.drop(missing_phenos, axis = 0)

In [11]:
X_train, X_test, y_train, y_test = train_test_split( geno, y, test_size=0.15)

In [12]:
X_train = X_train.drop(columns = ["Unnamed: 0"]).values
X_test = X_test.drop(columns = ["Unnamed: 0"]).values

y_train_std = (y_train - np.mean(y_train)) / np.std(y_train)
y_test_std = (y_test - np.mean(y_train)) / np.std(y_train)

In [13]:
ridge = RidgeCV(alphas = [10, 50, 100, 200, 1000, 1250, 1500, 1750, 2000, 2250, 2500, 2750, 3000], cv = None).fit(X_train, y_train_std)
print("Regularization alpha = ", ridge.alpha_)
y_pred = ridge.predict(X_test)
mse = mean_squared_error(y_pred, y_test_std)
r2 = r2_score( y_test_std, y_pred)

Regularization alpha =  1500

In [14]:
r2

0.55495435506527

In [15]:
mse

0.3979667881535281